global:
  scrape_interval:     1m
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    relabel_configs:
      - replacement: '{{AWS_ACCOUNT_ALIAS}}'
        target_label: aws_account_alias
